dialect = "postgresql"
host = "db.wcwiozumyufdtskudlvi.supabase.co"
port = "5432"
database = "estoque"
username = "postgres"
password = "Amoracolorida1!"

[connections.supabase]
SUPABASE_URL = "https://wcwiozumyufdtskudlvi.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indjd2lvenVteXVmZHRza3VkbHZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NjkxNDUsImV4cCI6MjA1NDQ0NTE0NX0.LReEt_mCPdGlvlbqn7y_Sw00X8_31xZRPsKw_W_6K48"
